### ISSUE TITLE
Les commentaires devraient être déplacés

### ISSUE THREAD

**Issue by Tointoin** [Lobabro/FizzBuzz#1]
https://github.com/Lobabro/FizzBuzz/blob/7d9212348089d86df07bb59ba940f8a71e7dc18e/Exo_Fizz-Buzz.py#L1-L9

Les commentaires avec les consignes en début de fichier devraient plutôt être dans un fichier README.md, accompagné de contexte (il s'agit d'un exercice d'entrainement, que fait le script python, comment l'utiliser, etc.)

**Comment by Lobabro** [comment]
C'est fait ! :)
